#
#  Makefile 	-- Makefile for the Toy compiler documentation
#
# Copyright © 2015 Erick Gallesio - Polytech Nice-Sophia <eg@unice.fr>
#
#           Author: Erick Gallesio [eg@unice.fr]
#    Creation date: 25-Jun-2015 11:46 (eg)
# Last file update: 18-Sep-2015 09:25 (eg)
#

all:	doc

doc:
	doxygen

clean:
	rm -f *~ doxygen_sqlite3.db

distclean: clean
	rm -rf html


